baseURL = 'https://cyf-signposts.netlify.app/'
title = 'CYF Signposts'
languageCode = "en-gb"

[params]
description = "Signposting resources for CodeYourFuture members"
repo = "https://github.com/CodeYourFuture/CYF-Signposts"

[taxonomies]
series = "regions"
tags = "topics"
