name: Developer issues
description: Raise an issue on the functionality not the content
title: "[Bug/Feature] <title>"
labels: [Development]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open an issue!
  - type: textarea
    id: issue-copy
    attributes:
      label: Describe issue here
      description: Please label with bug or feature
      placeholder: What did you expect to happen? /  What happened?
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**
