name: Propose feature
description: Propose a new feature for the website
title: "[Feature] <title>"
labels: [Development, Feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature! 
        Please read the contributing guidelines before continuing.
  - type: textarea
    id: feature-proposal
    attributes:
      label: Propose new feature
      description: Please include your user story or stories and then describe functionality with Given/When/Then
      placeholder: As a CYF trainee, I want to be able to...
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**
