backend:
  name: git-gateway
  branch: main
media_folder: static/img
public_folder: /img
collections:
  - name: "content"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: link, widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Internal CYF resource", name: "cyf", widget: "boolean" }
      - label: "Problem/Topic"
        name: "topics"
        widget: "list"
      - label: "CYF Region"
        name: "regions"
        widget: "select"
        options:
          - "Capetown"
          - "Glasgow"
          - "London"
          - "North West"
          - "West Midlands"
      - { label: "Body", name: "body", widget: "markdown" }
