backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "content"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: link, widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Problem/Topic"
        name: "topics"
        widget: "list"
        allow_add: true
      - label: "CYF Regions"
        name: "regions"
        widget: "list"
        field:
          label: "Region"
          name: "region"
          widget: "select"
          options:
            - "Capetown"
            - "Glasgow"
            - "London"
            - "North West"
            - "West Midlands"
      - { label: "Body", name: "body", widget: "markdown" }
