backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "entry"
    label: "Entry"
    folder: "content/entry"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: link, widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Region", name: "region", widget: "dropdown" }
      - { label: "CYF", name: "cyf", widget: "boolean" }
      - { label: "Topic", name: "topic", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
